### ISSUE TITLE
Sylius is not notify when payment success after first payment fail

### ISSUE THREAD

**Issue by rv-garnier** [FLUX-SE/SyliusPayumMoneticoPlugin#2]
When you fail the first attempt, sylius payment is marked as failed, but same reference is used if you make a new attempt. If it succeed, payment marked as failed can't be completed due to state machine usage, and is still awaiting payment.

Note : when a payment failed, Sylius create new payment with "new" state, and empty details. So, if customer fail first payment, but return to shop, he can retry with this new payment.

I didn't found solution now, an idea ?

**Comment by Prometee** [comment]
I will handle it after merging your PR, I was having nearly the same problem on another gateway and I think I could fix this.

Thanks for declaring an issue for it ;)

**Comment by Prometee** [comment]
Fixed and released into : https://github.com/Prometee/SyliusPayumMoneticoPlugin/releases/tag/v1.0.1

**Comment by sdechomets** [comment]
Hello,

It seems that we have version 1.0.1 installed, but the present bug is still present for us. Should we upgrade to the next version? And in this case, what is the procedure to follow knowing that the repository has changed?

Thx in advance

**Comment by Prometee** [comment]
Hello, to upgrade to the latest version follow : https://github.com/FLUX-SE/SyliusPayumMoneticoPlugin/blob/master/UPGRADE.md
You can also read the release note : https://github.com/FLUX-SE/SyliusPayumMoneticoPlugin/releases/tag/v1.1.0

But with v1.0.1 it's not possible that you have this kind of issue, unless you had change this provider return value :
https://github.com/FLUX-SE/SyliusPayumMoneticoPlugin/blob/master/src/Provider/ReferenceProvider.php

**Comment by sdechomets** [comment]
Thx for this answer, I'll investigate a little bit more (it's still not working) but our app code is totally messy. I think I've to clean the code before asking you for more. Sorry for the convenience.

**Comment by Prometee** [comment]
@sdechomets No problem, don't hesitate to make a PR if you found something 😉
